spring:
  application:
    name: google-drive-organizer
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
            - openid
            - profile
            - email
            - https://www.googleapis.com/auth/drive
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

drive:
  check-in-folder-id: ${GOOGLE_DRIVE_FOLDER_ID}

ocr:
  language: deu+eng
  tesseract-path: C:\\Program Files\\Tesseract-OCR
  tessdata-path: C:\\Program Files\\Tesseract-OCR\\tessdata

thumbnail:
  cache:
    directory: ${THUMBNAIL_CACHE_DIR:./cache/thumbnails}

server:
  port : 8081